---
title: "Manipulando variáveis categóricas no SEM"
---

Críticas específicas quanto ao tratamento de variáveis categóricas e ordinais no SEM tem sido um forte impedimento para seu uso mais amplo. O tratamento ingênuo de variáveis binárias e categóricas ordinais como se fossem normalmente distribuídas em algumas aplicações SEM foi em parte devido à falta de alternativas viáveis em seus primeiros dias. O uso inadequado de coeficientes de regressão padronizados como medidas de efeito em algumas aplicações SEM também foi criticado. Mesmo quando as propriedades distributivas das variáveis categóricas foram levadas em consideração, a interpretação das estimativas dos parâmetros SEM em termos de medidas de impacto, como risco atribuível, não foi aplicada. Erros padrão e limites de confiança – raramente usados em SEM – geralmente subestimam as incertezas do modelo estrutural, como a seleção de variáveis relevantes e a especificação correta de suas influências.

Uma revisão recente do tratamento de variáveis categóricas e outras variáveis não normais em SEM listou quatro estratégias principais: 

a) estimadores de distribuição assintótica livre (ADF) ajustando para não normalidade levando em consideração curtose na distribuição multivariada conjunta; 

b) o uso de estimativa robusta de máxima verossimilhança ou técnicas de reamostragem, como *jacknife* ou *bootstrap*, para obter os erros padrão dos parâmetros SEM, pois estes são mais afetados pelo desvio da normalidade multivariada 
c) calcular correlações polisseriais, tetracóricas ou policóricas para pares de variáveis com distribuição conjunta não normal assumindo que estes têm uma escala contínua subjacente (latente) cuja distribuição conjunta da amostra grande é normal bivariada, então usando essas correlações como entrada para SEM e;

d) estimar as *scores* do modelo probit ou logit para variáveis categóricas observadas como o primeiro nível, e então proceder com SEM com base nesses *scores* como o segundo nível. A estimativa ADF geralmente requer grandes amostras para manter o erro tipo II em um nível razoável e variáveis extremamente não normais, como a binária, pode ser difícil de lidar com precisão suficiente. 

As duas últimas estratégias dependem criticamente de quão bem o modelo de primeiro nível se ajusta aos dados.

Uma revisão de modelos estatísticos para dados categóricos revela a falta de um método capaz de lidar com mais de uma equação de regressão. Embora modelos log-lineares para tabelas de contingência possam analisar resultados categóricos relacionados e sua relação com variáveis independentes, interações possivelmente complexas entre as variáveis no modelo não indicam a direção das influências como nos modelos de regressão. Isso sublinha a necessidade de uma estrutura SEM para análise de dados categóricos para lidar com técnicas de redução de dimensionalidade e regressão dentro do mesmo modelo (a parte direita da Figura 1).

Dois grandes desenvolvimentos recentes no tratamento de dados categóricos incluem a extensão do SEM de Muthen para a abordagem de *modelagem de variável latente** e uma extensão de modelos lineares generalizados para variáveis latentes e mistas sob a estrutura GLLAMM (*Generalized Linear Latent And Mixed Models*). Apesar de terem origens estatísticas diferentes, tanto o software Mplus de Muthén e GLLAMM são capazes de modelar uma mistura de variáveis de escala contínua, ordinal e nominal, múltiplos grupos (incluindo clusters) e dados hierárquicos (multinível), efeitos aleatórios, dados perdidos, variáveis latentes (incluindo classes latentes e modelos de crescimento latente) e modelos de sobrevivência em tempo discreto. 

Ambos os desenvolvimentos são baseados na visão de modelos lineares generalizados como uma estrutura unificadora para variáveis contínuas e categóricas, onde as últimas são primeiramente transformadas em funções lineares contínuas e posteriormente modeladas por SEM. Este artigo segue a mesma linha, mas propõe uma transformação diferente para variáveis categóricas, até então não utilizadas em SEM. São apresentados um exemplo de dados simulados e reais com uma variável de confusão latente.
